server:
  port: 8081
spring:
  application:
    name: fraud
  zipkin:
    base-url: http://zipkin:9411
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/fraud
    username: abbes
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true